<?php

return <<<EOT
    body,
    .body input[type="text"],
    .body input[type="password"],
    .body textarea,
    .body select,
    .footer input[type="text"],
    .footer input[type="password"],
    .footer textarea, .footer select,
    .fancybox-container input[type="text"],
    .fancybox-container input[type="password"],
    .fancybox-container textarea,
    .fancybox-container select,
    .popup-window input[type="text"],
    .popup-window input[type="password"],
    .popup-window textarea,
    .popup-window select,
    .rsgppopup input[type="text"],
    .rsgppopup input[type="password"],
    .rsgppopup textarea,
    .rsgppopup select,
    .rs_easycart input[type="text"],
    .rs_easycart input[type="password"],
    .rs_easycart textarea,
    .rs_easycart select,
    .gopro-subscribe-window input[type="text"],
    .gopro-subscribe-window input[type="password"],
    .gopro-subscribe-window textarea,
    .gopro-subscribe-window select,
    .body .suggestion-items-form__button,
    .basket-item-property-name, 
    .basket-item-property-custom-name,
    .basket-item-info-name,
    .basket-item-info-name-link,
    .basket-coupon-block-field-description,
    .basket-coupon-block-total-price-difference,
    .basket-item-price-current-text,
    .basket-item-price-title,
    .basket-coupon-block-total-price-current,
    .basket-coupon-block-total-price-old,
    .basket-item-price-difference,
    .basket-item-property-value, 
    .basket-item-property-custom-value,
    .bx-soa-section-title,
    .c-prices.view-list.product-alone .c-prices__value,
    .product-delivery__title,
    .table > thead:first-child > tr:first-child > th,
    .body .sale-personal-profile-list-container > tbody > tr > th,
    .sale-order-list-shipment-button, 
    .sale-order-list-repeat-link, 
    .sale-order-list-cancel-link, 
    .sale-order-list-about-link, 
    .sale-order-list-change-payment,
    .sale-order-title,
    .sale-order-link, 
    .sale-order-history-link,
    .sale-order-detail-about-order-inner-container-list-item,
    .sale-order-detail-about-order-inner-container-name-titile,
    .sale-order-detail-about-order-inner-container-status-title,
    .sale-order-detail-about-order-inner-container-price-title,
    .sale-order-detail-payment-options-shipment-composition-item-title,
    .sale-order-detail-payment-options-order-content-item-title,
    .sale-order-detail-about-order-title-element, 
    .sale-order-detail-payment-options-title-element, 
    .sale-order-detail-payment-options-shipment-composition-title-element, 
    .sale-order-detail-payment-options-order-content-title-element,
    .sale-order-detail-general-item,
    .b-locations-top__bitrix-search .bx-sls .bx-ui-sls-container .bx-ui-sls-fake,
    .b-locations-top__bitrix-search .bx-sls .bx-ui-sls-container .bx-ui-sls-route,
    .sale-order-detail-total-payment-list-right-item,
    .sale-order-detail-about-order-inner-container-name-detail, 
    .sale-order-detail-about-order-inner-container-status-detail,
    .sale-order-detail-about-order-inner-container-price-detail,
    .sale-order-detail-payment-options-methods-shipment-list,
    .sale-order-detail-payment-options-methods-info-total-check, 
    .sale-order-detail-payment-options-methods-info-total-price,
    .sale-order-detail-payment-options-info-total-price,
    .sale-order-detail-payment-options-methods-button-element, 
    .sale-order-detail-payment-options-methods-button-element-new-window,
    .sale-order-detail-payment-options-methods-info-title-status-alert,
    .sale-order-detail-payment-options-methods-info-title-status-restricted, 
    .sale-order-detail-payment-options-methods-info-title-status-success,
    .sale-order-detail-payment-options-methods-info-change-link,
    .sale-order-detail-about-order-inner-container-repeat-cancel,
    .sale-order-detail-payment-options-info-order-number, 
    .sale-order-detail-payment-options-info-total-price,
    .sale-order-detail-about-order-inner-container-repeat-button,
    .sale-order-detail-payment-options-methods-info-title, 
    .sale-order-detail-payment-options-methods-shipment-list-item-title,
    .sale-order-detail-about-order-inner-container-list-item-element,
    .body .sale-order-detail .sale-order-detail-about-order-title > h3,
    .body .sale-order-detail .sale-order-detail-payment-options-title > h3,
    .body .sale-order-detail .sale-order-detail-payment-options-order-content-title > h3,
    .body .sale-order-detail .sale-order-detail-payment-options-shipment-composition-title-element > h3,
    div.soc-serv-title-grey,
    .sale-order-detail-title-element,
    .b-section-list a,
    b  { 
        font-family: "$sFontName", sans-serif;
    }
EOT;

?>