<?php
$aMenuLinks = array(
    array(
        "О компании",
        "/content/about/",
        array(),
        array(),
        ""
    ),
    array(
        "Услуги",
        "/content/services/",
        array(),
        array(),
        ""
    ),
    array(
        "Новости",
        "/content/news/",
        array(),
        array(),
        ""
    ),
    array(
        "Новинки",
        "/catalog/novinki/",
        array(),
        array(),
        ""
    ),
    array(
        "Документы",
        "/content/documents/",
        array(),
        array(),
        ""
    ),
    array(
        "Пресс-кит",
        "/content/press-kit/",
        array(),
        array(),
        ""
    ),
    array(
        "Снято с производства",
        "/catalog/out_of/",
        array(),
        array(),
        ""
    )
);
