<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "В нашем интернет-магазине мебели вы всегда можете купить мебель для вашей спальни по доступным ценам.");
$APPLICATION->SetPageProperty("keywords", "кровати, распродажа, мебель в спалью, дешево, мебель, в краснодаре, вешалки, эконом, с скидкой, петербург, москва, крд, всегда в наличии, зеркало, шкаф купе, шкаф, купе, диван, мягкая мебель, в кредит, по карте, казань, мск, спб, корпусная мебель, многомебели, вашакомната, горка, стенд,мебель, пенза, обставить, матрасы, трюмо, макияжные столы, стол гримера, магазин матрасов, основания для кроватей, комды, тумбы, тумбочки прикроватные, обставить мебелью спальню");
$APPLICATION->SetPageProperty("title", "ТД Андрей интернет-магазин все для для спальни в Москве, Санкт-Петербурге, Краснодаре и Казане.");
$APPLICATION->SetTitle("ТД Андрей каталог товаров по распродаже, акции и специальные предложения.");
$PRICE_NAME = ProGetLocalPriceName();
?>
<?$APPLICATION->IncludeComponent(
    "bitrix:catalog", 
    "gopro", 
    array(
        "FILTER_PRICE_CODE" => array(
            0 => $PRICE_NAME,
        ),
        "FILTER_PRICE_GROUPED" => array(
            0 => $PRICE_NAME,
        ),
        "PRICE_CODE" => array(
            0 => $PRICE_NAME,
        ),
        "IBLOCK_TYPE" => "catalog",
        "IBLOCK_ID" => "29",
        "SECTIONS_VIEW_MODE" => "VIEW_ELEMENTS",
        "HIDE_NOT_AVAILABLE" => "L",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SEF_MODE" => "Y",
        "SEF_FOLDER" => "/catalog/",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "CACHE_TYPE" => "N",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "ADD_ELEMENT_CHAIN" => "N",
        "USE_ELEMENT_COUNTER" => "Y",
        "USE_FILTER" => "Y",
        "FILTER_NAME" => "arrFilter",
        "FILTER_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "FILTER_PROPERTY_CODE" => array(
            0 => "SHIRINA",
            1 => "VISOTA",
            2 => "GLUBINA",
            3 => "SM",
            4 => "MATERIAL",
            5 => "",
        ),

        "FILTER_OFFERS_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "FILTER_OFFERS_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "PROPS_FILTER_COLORS" => "",

        "FILTER_PROP_SCROLL" => array(
        ),
        "FILTER_PROP_SEARCH" => array(
        ),
        "PROPS_SKU_FILTER_COLORS" => array(
            0 => "COLOR_DIRECTORY",
        ),
        "FILTER_SKU_PROP_SCROLL" => array(
        ),
        "FILTER_SKU_PROP_SEARCH" => array(
        ),
        "USE_REVIEW" => "Y",
        "MESSAGES_PER_PAGE" => "10",
        "USE_CAPTCHA" => "Y",
        "REVIEW_AJAX_POST" => "N",
        "PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
        "FORUM_ID" => "#COMMENTS_FORUM_ID#",
        "URL_TEMPLATES_READ" => "",
        "SHOW_LINK_TO_FORUM" => "N",
        "USE_COMPARE" => "Y",
        "COMPARE_NAME" => "CATALOG_COMPARE_LIST",
        "COMPARE_FIELD_CODE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "DETAIL_PICTURE",
            2 => "",
        ),
        "COMPARE_PROPERTY_CODE" => array(
            0 => "",
            1 => "CML2_ARTICLE",
            2 => "BRAND",
            3 => "YEAR",
            4 => "OS",
            5 => "WEIGHT",
            6 => "FORUM_MESSAGE_CNT",
            7 => "RSFAVORITE_COUNTER",
            8 => "FORUM_TOPIC_ID",
            9 => "HEIGHT",
            10 => "TICKNESS",
            11 => "WIDTH",
            12 => "DIAGONAL",
            13 => "SOLUTION",
            14 => "INTERNET_ACCESS",
            15 => "INTERFACES",
            16 => "NAVI",
            17 => "CARD",
            18 => "ACCESSORIES",
            19 => "POHOZHIE",
            20 => "BUY_WITH_THIS",
            21 => "YEARS",
            22 => "",
        ),
        "COMPARE_OFFERS_FIELD_CODE" => array(
            0 => "ID",
            1 => "CODE",
            2 => "XML_ID",
            3 => "NAME",
            4 => "TAGS",
            5 => "SORT",
            6 => "PREVIEW_TEXT",
            7 => "PREVIEW_PICTURE",
            8 => "DETAIL_TEXT",
            9 => "DETAIL_PICTURE",
            10 => "DATE_ACTIVE_FROM",
            11 => "ACTIVE_FROM",
            12 => "DATE_ACTIVE_TO",
            13 => "ACTIVE_TO",
            14 => "SHOW_COUNTER",
            15 => "SHOW_COUNTER_START",
            16 => "IBLOCK_TYPE_ID",
            17 => "IBLOCK_ID",
            18 => "IBLOCK_CODE",
            19 => "IBLOCK_NAME",
            20 => "IBLOCK_EXTERNAL_ID",
            21 => "DATE_CREATE",
            22 => "CREATED_BY",
            23 => "CREATED_USER_NAME",
            24 => "TIMESTAMP_X",
            25 => "MODIFIED_BY",
            26 => "USER_NAME",
            27 => "",
        ),
        "COMPARE_OFFERS_PROPERTY_CODE" => array(
            0 => "CML2_ARTICLE",
            1 => "COLOR_DIRECTORY",
            2 => "COLOR2_DIRECTORY",
            3 => "STORAGE",
            4 => "",
        ),
        "COMPARE_ELEMENT_SORT_FIELD" => "shows",
        "COMPARE_ELEMENT_SORT_ORDER" => "asc",
        "DISPLAY_ELEMENT_SELECT_BOX" => "N",

        "USE_PRICE_COUNT" => "Y",
        "SHOW_PRICE_COUNT" => "1",
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "Y",
        "CONVERT_CURRENCY" => "N",
        "BASKET_URL" => "/personal/cart/",
        "ACTION_VARIABLE" => "action",
        "PRODUCT_ID_VARIABLE" => "id",
        "USE_PRODUCT_QUANTITY" => "Y",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRODUCT_PROPERTIES" => "",
        "OFFERS_CART_PROPERTIES" => "",
        "SHOW_TOP_ELEMENTS" => "N",
        "SECTION_COUNT_ELEMENTS" => "Y",
        "SECTION_TOP_DEPTH" => "5",
        "PAGE_ELEMENT_COUNT" => "50",
        "LINE_ELEMENT_COUNT" => "4",
        "ELEMENT_SORT_FIELD" => "sort",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_FIELD2" => "id",
        "ELEMENT_SORT_ORDER2" => "desc",
        "LIST_PROPERTY_CODE" => array(
            0 => "CML2_ARTICLE",
            1 => "BRAND",
            2 => "YEAR",
            3 => "OS",
            4 => "WEIGHT",
            5 => "HEIGHT",
            6 => "TICKNESS",
            7 => "WIDTH",
            8 => "DIAGONAL",
            9 => "SOLUTION",
            10 => "INTERNET_ACCESS",
            11 => "INTERFACES",
            12 => "NAVI",
            13 => "CARD",
            14 => "VIDEO",
            15 => "ACCESSORIES",
            16 => "BUY_WITH_THIS",
            17 => "",
        ),
        "INCLUDE_SUBSECTIONS" => "A",
        "LIST_META_KEYWORDS" => "-",
        "LIST_META_DESCRIPTION" => "-",
        "LIST_BROWSER_TITLE" => "-",
        "LIST_OFFERS_FIELD_CODE" => array(
            0 => "ID",
            1 => "CODE",
            2 => "XML_ID",
            3 => "NAME",
            4 => "TAGS",
            5 => "SORT",
            6 => "PREVIEW_TEXT",
            7 => "PREVIEW_PICTURE",
            8 => "DETAIL_TEXT",
            9 => "DETAIL_PICTURE",
            10 => "DATE_ACTIVE_FROM",
            11 => "ACTIVE_FROM",
            12 => "DATE_ACTIVE_TO",
            13 => "ACTIVE_TO",
            14 => "SHOW_COUNTER",
            15 => "SHOW_COUNTER_START",
            16 => "IBLOCK_TYPE_ID",
            17 => "IBLOCK_ID",
            18 => "IBLOCK_CODE",
            19 => "IBLOCK_NAME",
            20 => "IBLOCK_EXTERNAL_ID",
            21 => "DATE_CREATE",
            22 => "CREATED_BY",
            23 => "CREATED_USER_NAME",
            24 => "TIMESTAMP_X",
            25 => "MODIFIED_BY",
            26 => "USER_NAME",
            27 => "",
        ),
        "LIST_OFFERS_PROPERTY_CODE" => array(
            0 => "CML2_ARTICLE",
            1 => "COLOR_DIRECTORY",
            2 => "COLOR2_DIRECTORY",
            3 => "STORAGE",
            4 => "MORE_PHOTO",
            5 => "",
        ),
        "LIST_OFFERS_LIMIT" => "0",
        "DETAIL_PROPERTY_CODE" => array(
            0 => "CML2_ARTICLE",
            1 => "BRAND",
            2 => "YEAR",
            3 => "OS",
            4 => "WEIGHT",
            5 => "HEIGHT",
            6 => "TICKNESS",
            7 => "WIDTH",
            8 => "DIAGONAL",
            9 => "SOLUTION",
            10 => "INTERNET_ACCESS",
            11 => "INTERFACES",
            12 => "NAVI",
            13 => "CARD",
            14 => "VIDEO",
            15 => "YEARS",
            16 => "",
        ),
        "DETAIL_META_KEYWORDS" => "-",
        "DETAIL_META_DESCRIPTION" => "-",
        "DETAIL_BROWSER_TITLE" => "-",
        "DETAIL_OFFERS_FIELD_CODE" => array(
            0 => "ID",
            1 => "CODE",
            2 => "XML_ID",
            3 => "NAME",
            4 => "TAGS",
            5 => "SORT",
            6 => "PREVIEW_TEXT",
            7 => "PREVIEW_PICTURE",
            8 => "DETAIL_TEXT",
            9 => "DETAIL_PICTURE",
            10 => "DATE_ACTIVE_FROM",
            11 => "ACTIVE_FROM",
            12 => "DATE_ACTIVE_TO",
            13 => "ACTIVE_TO",
            14 => "SHOW_COUNTER",
            15 => "SHOW_COUNTER_START",
            16 => "IBLOCK_TYPE_ID",
            17 => "IBLOCK_ID",
            18 => "IBLOCK_CODE",
            19 => "IBLOCK_NAME",
            20 => "IBLOCK_EXTERNAL_ID",
            21 => "DATE_CREATE",
            22 => "CREATED_BY",
            23 => "CREATED_USER_NAME",
            24 => "TIMESTAMP_X",
            25 => "MODIFIED_BY",
            26 => "USER_NAME",
            27 => "",
        ),
        "DETAIL_OFFERS_PROPERTY_CODE" => array(
            0 => "CML2_ARTICLE",
            1 => "COLOR_DIRECTORY",
            2 => "COLOR2_DIRECTORY",
            3 => "STORAGE",
            4 => "MORE_PHOTO",
            5 => "",
        ),
        "PROPS_TABS" => array(
        ),
        "USE_CHEAPER" => "N",
        "USE_BLOCK_MODS" => "N",
        "LINK_IBLOCK_TYPE" => "catalog",
        "LINK_IBLOCK_ID" => "2",
        "LINK_PROPERTY_SID" => "CML2_LINK",
        "LINK_ELEMENTS_URL" => "",
        "USE_ALSO_BUY" => "Y",
        "ALSO_BUY_ELEMENT_COUNT" => "5",
        "ALSO_BUY_MIN_BUYES" => "1",
        "USE_STORE" => "Y",
        "USE_STORE_PHONE" => "N",
        "USE_STORE_SCHEDULE" => "N",
        "USE_MIN_AMOUNT" => "N",
        "MIN_AMOUNT" => "10",
        "STORE_PATH" => "/store/#store_id#",
        "MAIN_TITLE" => "Наличие",
        "OFFERS_SORT_FIELD" => "sort",
        "OFFERS_SORT_ORDER" => "asc",
        "OFFERS_SORT_FIELD2" => "id",
        "OFFERS_SORT_ORDER2" => "desc",
        "PAGER_TEMPLATE" => "gopro",
        "DISPLAY_TOP_PAGER" => "Y",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "PAGER_TITLE" => "Товары",
        "PAGER_SHOW_ALWAYS" => "Y",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "Y",
        "PROP_MORE_PHOTO" => "MORE_PHOTO",
        "PROP_ARTICLE" => "-",
        "USE_FAVORITE" => "Y",
        "USE_SHARE" => "Y",
        "SHOW_ERROR_EMPTY_ITEMS" => "Y",
        "SHORT_SORTER" => "Y",
        "PROP_SKU_MORE_PHOTO" => "-",
        "PROP_SKU_ARTICLE" => "ID",
        "PROPS_ATTRIBUTES" => array(
        ),
        "PROPS_ATTRIBUTES_COLOR" => array(
            0 => "COLOR",
        ),
        "AJAX_OPTION_ADDITIONAL" => "",
        "FILTER_FIXED" => "Y",
        "DETAIL_TABS_VIEW" => "tab",
        "SHOW_PREVIEW_TEXT" => "Y",
        "YM_COUNTER_NUMBER_LOCATION" => "module",
        "YM_TARGET_NAME_ADD2BASKET" => "",
        "YM_TARGET_NAME_ADD2COMPARE" => "",
        "YM_TARGET_NAME_ADD2FAVORITE" => "",
        "DETAIL_SHOW_SIZE_TABLE" => "Y",
        "SIZE_TABLE_USER_FIELDS" => "UF_SIZE_TABLE",
        "SIZE_TABLE_PROP" => "-",
        "PROPS_ATTRIBUTES_SIZE" => "",
        "COMPONENT_TEMPLATE" => "gopro",
        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
        "USER_CONSENT" => "N",
        "USER_CONSENT_ID" => "1",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "N",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "DETAIL_STRICT_SECTION_CHECK" => "N",
        "SET_LAST_MODIFIED" => "N",
        "STICKERS_PROPS" => array(
            0 => "HIT",
            1 => "SALE",
            2 => "DISCOUNT",
        ),
        "STICKERS_DISCOUNT_VALUE" => "Y",
        "USE_RATING" => "Y",
        "USE_LAZYLOAD" => "N",
        "RATING_PROP_COUNT" => "-",
        "RATING_PROP_SUM" => "-",
        "DETAIL_REVIEW_SHOW_COUNT" => "Y",
        "YM_USE_TARGETS" => "N",
        "COMPOSITE_FRAME_MODE" => "N",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
        "FILTER_USE_AJAX" => "N",
        "FILTER_HIDE_PROP_COUNT" => "N",
        "OFF_MEASURE_RATION" => "N",
        "SEARCH_PAGE_RESULT_COUNT" => "50",
        "SEARCH_RESTART" => "Y",
        "SEARCH_NO_WORD_LOGIC" => "Y",
        "SEARCH_USE_LANGUAGE_GUESS" => "N",
        "SEARCH_CHECK_DATES" => "Y",
        "SECTIONS_DESCRIPTION_POSITION" => "top",
        "SECTION_BACKGROUND_IMAGE" => "-",
        "LIST_SKU_VIEW" => "buttons",
        "USE_AUTO_AJAXPAGES" => "Y",
        "SECTION_DESCRIPTION_POSITION" => "top",
        "COL_XS_6" => "Y",
        "OFF_HOVER_POPUP" => "N",
        "HIDE_AJAXPAGES_LINK" => "N",
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
        "DETAIL_BACKGROUND_IMAGE" => "-",
        "SHOW_DEACTIVATED" => "N",
        "DETAIL_SKU_VIEW" => "buttons",
        "USE_CUSTOM_COLLECTION" => "N",
        "USE_DELIVERY_COST_BLOCK" => "N",
        "USE_DELIVERY_COST_TAB" => "Y",
        "PROP_BRAND" => "BRANDS",
        "PROP_PRICES_NOTE" => "-",
        "OFF_BUY1CLICK" => "N",
        "IMPORTANT_PROPS" => array(
        ),
        "IMPORTANT_PROPS_LINK_TO_TAB" => "Y",
        "SOC_SHARE_ICON" => array(
            0 => "collections",
            1 => "vkontakte",
            2 => "facebook",
        ),
        "CUSTOM_COLLECTION_PROPERTY" => "-",
        "MODS_ELEMENT_COUNT" => "30",
        "DELIVERY_COST_PAY_LINK" => "",
        "DELIVERY_COST_DELIVERY_LINK" => "",
        "BRAND_DETAIL_SHOW_LOGO" => "N",
        "USE_GIFTS_DETAIL" => "Y",
        "USE_GIFTS_SECTION" => "Y",
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
        "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
        "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
        "GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
        "GIFTS_SHOW_OLD_PRICE" => "Y",
        "GIFTS_SHOW_NAME" => "Y",
        "GIFTS_SHOW_IMAGE" => "Y",
        "GIFTS_MESS_BTN_BUY" => "Выбрать",
        "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
        "STORES" => array(
            0 => "3",
            1 => "4",
            2 => "5",
            3 => "6",
            4 => "",
        ),
        "USER_FIELDS" => array(
            0 => "",
            1 => "",
        ),
        "FIELDS" => array(
            0 => "",
            1 => "",
        ),
        "SHOW_EMPTY_STORE" => "Y",
        "SHOW_GENERAL_STORE_INFORMATION" => "Y",
        "HIDE_IN_LIST" => "Y",
        "PROP_STORE_REPLACE_SECTION" => "0",
        "PROP_STORE_REPLACE_DETAIL" => "0",
        "STORE_REPLACE_IF_NOT_AVAILABLE" => "N",
        "USE_BIG_DATA" => "N",
        "BIG_DATA_RCM_TYPE" => "bestsell",
        "BIG_DATA_ELEMENT_COUNT" => "10",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "SHOW_404" => "N",
        "MESSAGE_404" => "",
        "COMPATIBLE_MODE" => "Y",
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
        "SEF_URL_TEMPLATES" => array(
            "sections" => "",
            "section" => "#SECTION_CODE_PATH#/",
            "element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
            "compare" => "compare/?action=#ACTION_CODE#",
            "smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
        ),
        "VARIABLE_ALIASES" => array(
            "compare" => array(
                "ACTION_CODE" => "action",
            ),
        )
    ),
    false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>